from setuptools import setup

setup(name='chatbotio',
      version='0.1',
      description='The funniest joke in the world',
      url='http://github.com/storborg/funniest',
      author='Flying Circus',
      author_email='flyingcircus@example.com',
      license='MIT',
      packages=['chatbotapp'],
      zip_safe=False,
      install_requires=[
            'Flask==0.12.2',
            'Flask-Login==0.4.0',
            'Flask-Session==0.3.1',
            'Flask_SocketIO',
            'itsdangerous==0.24',
            'Jinja2==2.7.3',
            'MarkupSafe==0.23',
            'python-engineio',
            'python-socketio',
            'six==1.9.0',
            'Werkzeug==0.12.2',
            'certifi==2018.10.15',
            'chardet==3.0.4',
            'ChatterBot==0.8.7',
            'chatterbot-corpus==1.1.4',
            'future==0.17.1',
            'idna==2.7',
            'mathparse==0.1.2',
            'nltk==3.4.5',
            'oauthlib==2.1.0',
            'pymongo==3.7.2',
            'python-dateutil==2.6.1',
            'python-twitter==3.5',
            'PyYAML==3.13',
            'requests==2.20.0',
            'requests-oauthlib==1.0.0',
            'six==1.11.0',
            'SQLAlchemy==1.2.13',
            'urllib3==1.24.1',
            'eventlet'
      ]
      )